version: '2.1'
services:
   nginx:
      build:
         context: "${DOCKER_COMPOSE_NGINX_DIR:-./}build/docker-nginx"
         dockerfile: Dockerfile
      image: nginx:latest
      ports:
         - "80:80"
         - "443:443"
      volumes:
         - "${DOCKER_COMPOSE_NGINX_DIR:-./}run/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
         - "${DOCKER_COMPOSE_NGINX_DIR:-./}run/etc/nginx/conf.d/:/etc/nginx/conf.d/:ro"
         - "${DOCKER_COMPOSE_NGINX_DIR:-./}run/etc/nginx/sites-available/:/etc/nginx/sites-available/:ro"
         - "${DOCKER_COMPOSE_NGINX_DIR:-./}run/etc/nginx/sites-enabled/:/etc/nginx/sites-enabled/:ro"

